version: '3.8'

services:
  memecast-server:
    build: .
    container_name: memecast-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - SERVER_HOST=0.0.0.0
